- name: Start Minikube
  command: minikube start --driver=docker
  register: minikube_start_output

- name: Check Minikube status
  command: minikube status
  register: minikube_status_output

- name: Debug Minikube status
  debug:
    var: minikube_status_output.stdout_lines

- name: Verify Minikube cluster is running
  assert:
    that:
      - "'Running' in minikube_status_output.stdout"
    fail_msg: "Minikube cluster is not running"
    success_msg: "Minikube cluster is running successfully"

# - name: Set up Docker environment for Minikube
#   shell: eval $(minikube docker-env)
#   args:
#     executable: /bin/bash

- name: Pull application Docker image
  command: docker pull busybox

- name: Deploy application deployment
  copy:
    src: "{{ playbook_dir }}/roles/deploy_app/templates/init-container-deployment.yaml"
    dest: /home/{{ ansible_user }}/init-container-deployment.yaml

- name: Apply deployment configuration
  shell: kubectl apply -f /home/{{ ansible_user }}/init-container-deployment.yaml
