- name: Pull application Docker image
  command: docker pull busybox

- name: Deploy application deployment
  copy:
    src: "{{ playbook_dir }}/roles/deploy_app/templates/init-container-deployment.yaml"
    dest: /home/{{ ansible_user }}/init-container-deployment.yaml

- name: Apply deployment configuration
  shell: kubectl apply -f /home/{{ ansible_user }}/init-container-deployment.yaml
